// God-Mode v2 §2.1 — dispatcher secret-hygiene pin.
//
// This vitest locks in the security invariants of the outbound
// `WebhookDispatcher`: refuse to instantiate with an insecure secret,
// actually use the supplied secret when generating signatures, and
// verify them back under `verifySignature` with the same key.
//
// Before this file existed, the constructor silently fell back to the
// literal string `"default-secret"` when `WEBHOOK_SECRET` was unset —
// a signature forgery waiting to happen.
//
// Style: no Prisma, no `fetch`, no mail. We only hit the
// constructor, the private `generateSignature` (via the
// `testWebhook` path is avoided because it would open a socket), and
// the public static `verifySignature`. That keeps the test in the
// "pure" class the rest of the codebase's security invariants use.

import { createHmac } from "node:crypto";
import { describe, expect, it } from "vitest";

import { WebhookDispatcher } from "./dispatcher";

const SECRET = "test-secret-at-least-32-characters-long-xx";

describe("WebhookDispatcher — secret hygiene", () => {
  it("throws when constructed with no secret (env unset + no arg)", () => {
    expect(() => new WebhookDispatcher(undefined)).toThrow(/non-empty HMAC secret/i);
  });

  it("throws when constructed with an empty string secret", () => {
    expect(() => new WebhookDispatcher("")).toThrow(/non-empty HMAC secret/i);
  });

  it("throws when constructed with a whitespace-only secret", () => {
    expect(() => new WebhookDispatcher("   ")).toThrow(/non-empty HMAC secret/i);
  });

  it("accepts an explicit non-empty secret", () => {
    expect(() => new WebhookDispatcher(SECRET)).not.toThrow();
  });
});

describe("WebhookDispatcher — signature verification", () => {
  it("verifySignature returns true for a signature generated with the same secret", () => {
    const payload = JSON.stringify({ event: "webhook.test", at: "2026-04-18T00:00:00.000Z" });
    const sig = `sha256=${createHmac("sha256", SECRET).update(payload).digest("hex")}`;

    expect(WebhookDispatcher.verifySignature(payload, sig, SECRET)).toBe(true);
  });

  it("verifySignature returns false for a tampered payload", () => {
    const payload = JSON.stringify({ event: "webhook.test" });
    const sig = `sha256=${createHmac("sha256", SECRET).update(payload).digest("hex")}`;
    const tampered = JSON.stringify({ event: "webhook.hijack" });

    expect(WebhookDispatcher.verifySignature(tampered, sig, SECRET)).toBe(false);
  });

  it("verifySignature returns false when the secret differs", () => {
    const payload = JSON.stringify({ event: "webhook.test" });
    const sig = `sha256=${createHmac("sha256", SECRET).update(payload).digest("hex")}`;

    expect(
      WebhookDispatcher.verifySignature(
        payload,
        sig,
        "different-secret-at-least-32-characters-long-xx",
      ),
    ).toBe(false);
  });

  it("verifySignature refuses the literal 'default-secret' regression", () => {
    // Regression guard: the previous implementation defaulted to the
    // string "default-secret". If someone reintroduces that default,
    // a signature generated by the dispatcher would verify against
    // "default-secret" — which is exactly the forgery vector we're
    // preventing. This test documents the intent: a signature made
    // with "default-secret" must never match a signature over the
    // same payload using the real key.
    const payload = JSON.stringify({ event: "webhook.test" });
    const sigWithWeakKey = `sha256=${createHmac("sha256", "default-secret")
      .update(payload)
      .digest("hex")}`;

    expect(WebhookDispatcher.verifySignature(payload, sigWithWeakKey, SECRET)).toBe(false);
  });
});
