// P1-4 (audit v1.1 §5.19) — behavior pinning for
// `settings/security/actions.ts`.
//
// This module is deliberately on the personal-scope allowlist in
// `src/app/actions-contract.test.ts` — it manages per-user 2FA and
// there is no org-level capability that should gate it. That makes
// the contract looser in one place (no hasCapability) and TIGHTER
// in another (verification-before-write is the security property).
//
// Invariants pinned:
//
//   1. Enable and activate are separate actions. The secret +
//      backup codes are generated by `enableTwoFactorAction`, but
//      `enabled` stays `false` until `verifyAndActivateTwoFactorAction`
//      validates the user's TOTP code. This "setup then verify"
//      split prevents activation from a stolen session that never
//      confirmed the authenticator app.
//   2. Disable requires a fresh credential — either a valid TOTP
//      code OR a valid backup code. No bare "disable 2FA" path.
//   3. Regenerate backup codes also requires TOTP verification.
//      Without this, a logged-in session could quietly rotate
//      codes and lock out the real owner.
//   4. Backup codes are stored HASHED. A pre-audit regression would
//      have been storing plaintext; the test asserts hashedCodes
//      make it into the DB row (backupCodes: backupCodesHashed).
//   5. Double-enable is rejected — both enable and activate throw
//      if 2FA is already on, so a second setup flow cannot
//      overwrite the working one.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const SOURCE = readFileSync(resolve(__dirname, "actions.ts"), "utf8");

function sliceAction(start: string, end: string): string {
  const startIdx = SOURCE.indexOf(start);
  expect(startIdx, `${start} must appear in settings/security/actions.ts`).toBeGreaterThan(-1);
  const endIdx = SOURCE.indexOf(end, startIdx + start.length);
  expect(endIdx, `${end} must follow ${start}`).toBeGreaterThan(startIdx);
  return SOURCE.slice(startIdx, endIdx);
}

const ENABLE = sliceAction(
  "export async function enableTwoFactorAction",
  "export async function verifyAndActivateTwoFactorAction",
);
const ACTIVATE = sliceAction(
  "export async function verifyAndActivateTwoFactorAction",
  "export async function disableTwoFactorAction",
);
const DISABLE = sliceAction(
  "export async function disableTwoFactorAction",
  "export async function regenerateBackupCodesAction",
);
const REGEN = sliceAction(
  "export async function regenerateBackupCodesAction",
  "export async function getTwoFactorStatusAction",
);
// getTwoFactorStatusAction is the last export — slice to end-of-file.
const STATUS = (() => {
  const start = SOURCE.indexOf("export async function getTwoFactorStatusAction");
  expect(start, "getTwoFactorStatusAction must be exported").toBeGreaterThan(-1);
  return SOURCE.slice(start);
})();

describe("P1-4 settings/security/actions.ts — module shape", () => {
  it("is a 'use server' module", () => {
    expect(SOURCE.trimStart().startsWith('"use server"')).toBe(true);
  });

  it("intentionally omits hasCapability (personal-scoped, see actions-contract.test.ts)", () => {
    // 2FA is per-user; there is no org-level capability for
    // "let someone else enable 2FA on my account". If this
    // assertion ever fires, either add a real capability to
    // permissions.ts OR leave 2FA on the personal-scope allowlist.
    expect(SOURCE).not.toMatch(/\bhasCapability\s*\(/);
  });

  it("gates every action on requireActiveMembership (still org-aware)", () => {
    // Even though there's no capability check, every action
    // must confirm the caller has an active session — otherwise
    // an unauthenticated client could disable 2FA by calling the
    // raw server action directly.
    const count = (SOURCE.match(/requireActiveMembership\(\)/g) ?? []).length;
    // 5 actions (enable, activate, disable, regen, status).
    expect(count).toBeGreaterThanOrEqual(5);
  });
});

describe("P1-4 enableTwoFactorAction — setup without activation", () => {
  it("throws if 2FA is already enabled (no silent overwrite)", () => {
    expect(ENABLE).toMatch(/existing\?\.enabled[\s\S]*?throw new Error/);
  });

  it("writes enabled:false so activation requires a second step", () => {
    // The load-bearing bit: this action generates the secret but
    // leaves `enabled:false` in the DB until verifyAndActivate
    // runs. Skipping this split would let a stolen session enable
    // 2FA without ever proving possession of an authenticator.
    expect(ENABLE).toMatch(/enabled:\s*false/);
  });

  it("stores HASHED backup codes, never the plain ones", () => {
    // `backupCodes: backupCodesHashed` must appear in both upsert
    // branches (create and update).
    expect(ENABLE).toMatch(/backupCodes:\s*backupCodesHashed/);
    // And the return payload hands back the plain ones so the
    // UI can show them to the user exactly once.
    expect(ENABLE).toMatch(/return\s*\{[\s\S]*?backupCodes,/);
  });

  it("clears verifiedAt on re-setup (invalidates any old activation)", () => {
    expect(ENABLE).toMatch(/verifiedAt:\s*null/);
  });
});

describe("P1-4 verifyAndActivateTwoFactorAction — require TOTP verification", () => {
  it("throws if there is no pending setup row", () => {
    expect(ACTIVATE).toMatch(/!twoFactorAuth[\s\S]*?throw new Error/);
  });

  it("throws if 2FA is already enabled (no double-activate)", () => {
    expect(ACTIVATE).toMatch(/twoFactorAuth\.enabled[\s\S]*?throw new Error/);
  });

  it("returns false (not throws) on a bad TOTP code", () => {
    // Returning false instead of throwing gives the UI a clean
    // "try again" path; a thrown error would bubble up as a
    // generic server error and confuse users who mistyped once.
    expect(ACTIVATE).toMatch(/!isValid[\s\S]*?return false/);
  });

  it("flips enabled:true AND stamps verifiedAt on success", () => {
    expect(ACTIVATE).toMatch(/enabled:\s*true/);
    expect(ACTIVATE).toMatch(/verifiedAt:\s*now/);
  });
});

describe("P1-4 disableTwoFactorAction — fresh-credential gate", () => {
  it("throws if 2FA is not currently enabled", () => {
    expect(DISABLE).toMatch(/!twoFactorAuth\?\.enabled[\s\S]*?throw new Error/);
  });

  it("accepts a valid TOTP code as proof of possession", () => {
    expect(DISABLE).toMatch(/verifyTotpCode\(twoFactorAuth\.secret,\s*code\)/);
  });

  it("falls back to backup-code verification if TOTP fails", () => {
    // Users who've lost their phone MUST still be able to disable
    // 2FA using a backup code. If this branch disappears, you've
    // broken the account-recovery path.
    expect(DISABLE).toMatch(/verifyBackupCode\(code,\s*twoFactorAuth\.backupCodes\)/);
  });

  it("deletes the 2FA row on successful disable (no zombie secret)", () => {
    // Two delete calls — one after TOTP path, one after backup.
    const deletes =
      DISABLE.match(/db\.twoFactorAuth\.delete\(\s*\{[\s\S]*?where:\s*\{\s*userId\s*\}/g) ?? [];
    expect(deletes.length).toBeGreaterThanOrEqual(2);
  });

  it("returns false if neither code is valid (no silent downgrade)", () => {
    expect(DISABLE).toMatch(/return\s+false/);
  });
});

describe("P1-4 regenerateBackupCodesAction — requires TOTP", () => {
  it("throws if 2FA is not enabled", () => {
    expect(REGEN).toMatch(/!twoFactorAuth\?\.enabled[\s\S]*?throw new Error/);
  });

  it("verifies TOTP before issuing fresh codes", () => {
    // A logged-in session without TOTP possession must not be
    // able to rotate backup codes — that would let an attacker
    // shut the real owner out.
    expect(REGEN).toMatch(/verifyTotpCode\(twoFactorAuth\.secret,\s*code\)/);
    expect(REGEN).toMatch(/!isValid[\s\S]*?return null/);
  });

  it("stores only HASHED codes in the DB", () => {
    expect(REGEN).toMatch(/backupCodes:\s*hashed/);
  });

  it("returns PLAIN codes to the caller (one-time display)", () => {
    expect(REGEN).toMatch(/return\s+plain/);
  });
});

describe("P1-4 getTwoFactorStatusAction — read-only surface", () => {
  it("returns a stable shape with enabled/verifiedAt/createdAt/backupCodesRemaining", () => {
    expect(STATUS).toMatch(/enabled:\s*twoFactorAuth\?\.enabled\s*\?\?\s*false/);
    expect(STATUS).toMatch(/verifiedAt:\s*twoFactorAuth\?\.verifiedAt\s*\?\?\s*null/);
    expect(STATUS).toMatch(/createdAt:\s*twoFactorAuth\?\.createdAt\s*\?\?\s*null/);
    expect(STATUS).toMatch(/backupCodesRemaining:\s*twoFactorAuth\?\.backupCodes\.length/);
  });

  it("uses a narrow Prisma select (no secret, no hashed codes leak)", () => {
    // The findUnique MUST use select so we never accidentally
    // return the TOTP secret or the hashed backup codes to the
    // client. If this fires, someone widened the read and the
    // client is now exposed to material it shouldn't see.
    expect(STATUS).toMatch(
      /db\.twoFactorAuth\.findUnique\(\s*\{[\s\S]*?select:\s*\{[\s\S]*?enabled:\s*true/,
    );
    const select = STATUS.match(/select:\s*\{([\s\S]*?)\}/)?.[1] ?? "";
    expect(select).not.toMatch(/\bsecret:\s*true\b/);
  });
});
